### PR TITLE
fix: get all prompt templates #18

### LINKED ISSUE #18: get all prompt templates
We also want to expose a function which users can use to fetch all the prompt templates they have in our system. This will also behave similar to our python sdk.

### PR DESCRIPTION
**Pull request by abubakarsohail**
fix #18

This PR adds support for fetching all prompts from PromptLayer.

### CODE REVIEW

**Comment by abubakarsohail** [comment]
```ts
import promptlayer from "promptlayer";

async function main() {
  const response = await promptlayer.prompts.all({ page: 2, per_page: 4 });
  console.log(response);
}

main();
```

File: src/utils.ts [hunk 1]
```diff
@@ -53,6 +53,35 @@ const promptLayerApiRequest = async (body: TrackRequest) => {
...
+      console.warn(
+        `WARNING: While fetching all prompts, PromptLayer had the following error: ${JSON.stringify(
+          data
+        )}`
+      );
+    }
+    return data;
+  } catch (e) {
+    console.warn(
+      `WARNING: While fetching all prompts, PromptLayer had the following error: ${e}`
```
Comment (jzone3) [inline src/utils.ts:80]: Again, "prompt templates" not prompts.

And make this match the other messages in wording

**Review by jzone3 — DISMISSED** [review]
Fix error then good to merge
